{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ydb

  annotations:
    assign.ukserp.ac.uk/component: "ydb"
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: ydb
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ include "assign.labels.chart" . }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}

  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: ydb
            port:
              number: {{ .Values.service.port }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
