services:
  db:
    image: harbor.ukserp.ac.uk/linkage/assign:pr-8
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - type: volume
        source: db-data
        target: /data
volumes:
  db-data: